### ISSUE TITLE
Special character problem

### ISSUE THREAD

**Issue by next-direction** [rashid2538/php-htmldiff#3]
Hi,

I like you class, but I had a problem with german characters like ä, ü, ö.

Solution for me is, to replace the Explode funtion with the following code:

private function Explode( $value ) {
    return preg_split('//u', $value);
}

That splits a string using UTF8 encoding.

**Comment by ferrizzi** [comment]
There's still an issue, try diffing "Crédito" and "Créditos", it results in "Cré<del>dito</del><ins>ditos</ins>"
